#Aplication name
spring:
  application:
    name: Public-RestService
#Component info
info:
  component: Public-RestService
#Aleatorio
server:
  port: 0
#Eureka instance ID
eureka:
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#Service Registration Method
cloud:
  services:
    registrationMethod: route
#Disable HTTP basic Authentication
security:
  basic:
    enable: false